// Generated by gencpp from file roah_rsbb_comm_ros/GoalOMF.msg
// DO NOT EDIT!


#ifndef ROAH_RSBB_COMM_ROS_MESSAGE_GOALOMF_H
#define ROAH_RSBB_COMM_ROS_MESSAGE_GOALOMF_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roah_rsbb_comm_ros
{
template <class ContainerAllocator>
struct GoalOMF_
{
  typedef GoalOMF_<ContainerAllocator> Type;

  GoalOMF_()
    : initial_state()
    , switches()  {
    }
  GoalOMF_(const ContainerAllocator& _alloc)
    : initial_state(_alloc)
    , switches(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _initial_state_type;
  _initial_state_type initial_state;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _switches_type;
  _switches_type switches;





  typedef boost::shared_ptr< ::roah_rsbb_comm_ros::GoalOMF_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roah_rsbb_comm_ros::GoalOMF_<ContainerAllocator> const> ConstPtr;

}; // struct GoalOMF_

typedef ::roah_rsbb_comm_ros::GoalOMF_<std::allocator<void> > GoalOMF;

typedef boost::shared_ptr< ::roah_rsbb_comm_ros::GoalOMF > GoalOMFPtr;
typedef boost::shared_ptr< ::roah_rsbb_comm_ros::GoalOMF const> GoalOMFConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roah_rsbb_comm_ros::GoalOMF_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roah_rsbb_comm_ros::GoalOMF_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roah_rsbb_comm_ros::GoalOMF_<ContainerAllocator1> & lhs, const ::roah_rsbb_comm_ros::GoalOMF_<ContainerAllocator2> & rhs)
{
  return lhs.initial_state == rhs.initial_state &&
    lhs.switches == rhs.switches;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roah_rsbb_comm_ros::GoalOMF_<ContainerAllocator1> & lhs, const ::roah_rsbb_comm_ros::GoalOMF_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roah_rsbb_comm_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roah_rsbb_comm_ros::GoalOMF_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roah_rsbb_comm_ros::GoalOMF_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roah_rsbb_comm_ros::GoalOMF_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roah_rsbb_comm_ros::GoalOMF_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roah_rsbb_comm_ros::GoalOMF_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roah_rsbb_comm_ros::GoalOMF_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roah_rsbb_comm_ros::GoalOMF_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ecb2b723fb091fc72a4100a7999df09";
  }

  static const char* value(const ::roah_rsbb_comm_ros::GoalOMF_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ecb2b723fb091fcULL;
  static const uint64_t static_value2 = 0x72a4100a7999df09ULL;
};

template<class ContainerAllocator>
struct DataType< ::roah_rsbb_comm_ros::GoalOMF_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roah_rsbb_comm_ros/GoalOMF";
  }

  static const char* value(const ::roah_rsbb_comm_ros::GoalOMF_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roah_rsbb_comm_ros::GoalOMF_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool[] initial_state\n"
"uint32[] switches\n"
;
  }

  static const char* value(const ::roah_rsbb_comm_ros::GoalOMF_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roah_rsbb_comm_ros::GoalOMF_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.initial_state);
      stream.next(m.switches);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoalOMF_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roah_rsbb_comm_ros::GoalOMF_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roah_rsbb_comm_ros::GoalOMF_<ContainerAllocator>& v)
  {
    s << indent << "initial_state[]" << std::endl;
    for (size_t i = 0; i < v.initial_state.size(); ++i)
    {
      s << indent << "  initial_state[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.initial_state[i]);
    }
    s << indent << "switches[]" << std::endl;
    for (size_t i = 0; i < v.switches.size(); ++i)
    {
      s << indent << "  switches[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.switches[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROAH_RSBB_COMM_ROS_MESSAGE_GOALOMF_H
