// Generated by gencpp from file roah_rsbb_comm_ros/GoalHGMF.msg
// DO NOT EDIT!


#ifndef ROAH_RSBB_COMM_ROS_MESSAGE_GOALHGMF_H
#define ROAH_RSBB_COMM_ROS_MESSAGE_GOALHGMF_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace roah_rsbb_comm_ros
{
template <class ContainerAllocator>
struct GoalHGMF_
{
  typedef GoalHGMF_<ContainerAllocator> Type;

  GoalHGMF_()
    : object_type(0)
    , target_pose()  {
    }
  GoalHGMF_(const ContainerAllocator& _alloc)
    : object_type(0)
    , target_pose(_alloc)  {
  (void)_alloc;
    }



   typedef uint16_t _object_type_type;
  _object_type_type object_type;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _target_pose_type;
  _target_pose_type target_pose;





  typedef boost::shared_ptr< ::roah_rsbb_comm_ros::GoalHGMF_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roah_rsbb_comm_ros::GoalHGMF_<ContainerAllocator> const> ConstPtr;

}; // struct GoalHGMF_

typedef ::roah_rsbb_comm_ros::GoalHGMF_<std::allocator<void> > GoalHGMF;

typedef boost::shared_ptr< ::roah_rsbb_comm_ros::GoalHGMF > GoalHGMFPtr;
typedef boost::shared_ptr< ::roah_rsbb_comm_ros::GoalHGMF const> GoalHGMFConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roah_rsbb_comm_ros::GoalHGMF_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roah_rsbb_comm_ros::GoalHGMF_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roah_rsbb_comm_ros::GoalHGMF_<ContainerAllocator1> & lhs, const ::roah_rsbb_comm_ros::GoalHGMF_<ContainerAllocator2> & rhs)
{
  return lhs.object_type == rhs.object_type &&
    lhs.target_pose == rhs.target_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roah_rsbb_comm_ros::GoalHGMF_<ContainerAllocator1> & lhs, const ::roah_rsbb_comm_ros::GoalHGMF_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roah_rsbb_comm_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roah_rsbb_comm_ros::GoalHGMF_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roah_rsbb_comm_ros::GoalHGMF_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roah_rsbb_comm_ros::GoalHGMF_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roah_rsbb_comm_ros::GoalHGMF_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roah_rsbb_comm_ros::GoalHGMF_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roah_rsbb_comm_ros::GoalHGMF_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roah_rsbb_comm_ros::GoalHGMF_<ContainerAllocator> >
{
  static const char* value()
  {
    return "07dbf37e269caf1d027e61f1714cfbe7";
  }

  static const char* value(const ::roah_rsbb_comm_ros::GoalHGMF_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x07dbf37e269caf1dULL;
  static const uint64_t static_value2 = 0x027e61f1714cfbe7ULL;
};

template<class ContainerAllocator>
struct DataType< ::roah_rsbb_comm_ros::GoalHGMF_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roah_rsbb_comm_ros/GoalHGMF";
  }

  static const char* value(const ::roah_rsbb_comm_ros::GoalHGMF_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roah_rsbb_comm_ros::GoalHGMF_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 object_type\n"
"geometry_msgs/Pose2D target_pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::roah_rsbb_comm_ros::GoalHGMF_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roah_rsbb_comm_ros::GoalHGMF_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_type);
      stream.next(m.target_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoalHGMF_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roah_rsbb_comm_ros::GoalHGMF_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roah_rsbb_comm_ros::GoalHGMF_<ContainerAllocator>& v)
  {
    s << indent << "object_type: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.object_type);
    s << indent << "target_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.target_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROAH_RSBB_COMM_ROS_MESSAGE_GOALHGMF_H
