// Generated by gencpp from file roah_rsbb_comm_ros/Override.msg
// DO NOT EDIT!


#ifndef ROAH_RSBB_COMM_ROS_MESSAGE_OVERRIDE_H
#define ROAH_RSBB_COMM_ROS_MESSAGE_OVERRIDE_H

#include <ros/service_traits.h>


#include <roah_rsbb_comm_ros/OverrideRequest.h>
#include <roah_rsbb_comm_ros/OverrideResponse.h>


namespace roah_rsbb_comm_ros
{

struct Override
{

typedef OverrideRequest Request;
typedef OverrideResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Override
} // namespace roah_rsbb_comm_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roah_rsbb_comm_ros::Override > {
  static const char* value()
  {
    return "616a9e24da0705b47816f8443dff5147";
  }

  static const char* value(const ::roah_rsbb_comm_ros::Override&) { return value(); }
};

template<>
struct DataType< ::roah_rsbb_comm_ros::Override > {
  static const char* value()
  {
    return "roah_rsbb_comm_ros/Override";
  }

  static const char* value(const ::roah_rsbb_comm_ros::Override&) { return value(); }
};


// service_traits::MD5Sum< ::roah_rsbb_comm_ros::OverrideRequest> should match
// service_traits::MD5Sum< ::roah_rsbb_comm_ros::Override >
template<>
struct MD5Sum< ::roah_rsbb_comm_ros::OverrideRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roah_rsbb_comm_ros::Override >::value();
  }
  static const char* value(const ::roah_rsbb_comm_ros::OverrideRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roah_rsbb_comm_ros::OverrideRequest> should match
// service_traits::DataType< ::roah_rsbb_comm_ros::Override >
template<>
struct DataType< ::roah_rsbb_comm_ros::OverrideRequest>
{
  static const char* value()
  {
    return DataType< ::roah_rsbb_comm_ros::Override >::value();
  }
  static const char* value(const ::roah_rsbb_comm_ros::OverrideRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roah_rsbb_comm_ros::OverrideResponse> should match
// service_traits::MD5Sum< ::roah_rsbb_comm_ros::Override >
template<>
struct MD5Sum< ::roah_rsbb_comm_ros::OverrideResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roah_rsbb_comm_ros::Override >::value();
  }
  static const char* value(const ::roah_rsbb_comm_ros::OverrideResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roah_rsbb_comm_ros::OverrideResponse> should match
// service_traits::DataType< ::roah_rsbb_comm_ros::Override >
template<>
struct DataType< ::roah_rsbb_comm_ros::OverrideResponse>
{
  static const char* value()
  {
    return DataType< ::roah_rsbb_comm_ros::Override >::value();
  }
  static const char* value(const ::roah_rsbb_comm_ros::OverrideResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROAH_RSBB_COMM_ROS_MESSAGE_OVERRIDE_H
