// Generated by gencpp from file roah_rsbb_comm_ros/Percentage.msg
// DO NOT EDIT!


#ifndef ROAH_RSBB_COMM_ROS_MESSAGE_PERCENTAGE_H
#define ROAH_RSBB_COMM_ROS_MESSAGE_PERCENTAGE_H

#include <ros/service_traits.h>


#include <roah_rsbb_comm_ros/PercentageRequest.h>
#include <roah_rsbb_comm_ros/PercentageResponse.h>


namespace roah_rsbb_comm_ros
{

struct Percentage
{

typedef PercentageRequest Request;
typedef PercentageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Percentage
} // namespace roah_rsbb_comm_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roah_rsbb_comm_ros::Percentage > {
  static const char* value()
  {
    return "7c8164229e7d2c17eb95e9231617fdee";
  }

  static const char* value(const ::roah_rsbb_comm_ros::Percentage&) { return value(); }
};

template<>
struct DataType< ::roah_rsbb_comm_ros::Percentage > {
  static const char* value()
  {
    return "roah_rsbb_comm_ros/Percentage";
  }

  static const char* value(const ::roah_rsbb_comm_ros::Percentage&) { return value(); }
};


// service_traits::MD5Sum< ::roah_rsbb_comm_ros::PercentageRequest> should match
// service_traits::MD5Sum< ::roah_rsbb_comm_ros::Percentage >
template<>
struct MD5Sum< ::roah_rsbb_comm_ros::PercentageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roah_rsbb_comm_ros::Percentage >::value();
  }
  static const char* value(const ::roah_rsbb_comm_ros::PercentageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roah_rsbb_comm_ros::PercentageRequest> should match
// service_traits::DataType< ::roah_rsbb_comm_ros::Percentage >
template<>
struct DataType< ::roah_rsbb_comm_ros::PercentageRequest>
{
  static const char* value()
  {
    return DataType< ::roah_rsbb_comm_ros::Percentage >::value();
  }
  static const char* value(const ::roah_rsbb_comm_ros::PercentageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roah_rsbb_comm_ros::PercentageResponse> should match
// service_traits::MD5Sum< ::roah_rsbb_comm_ros::Percentage >
template<>
struct MD5Sum< ::roah_rsbb_comm_ros::PercentageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roah_rsbb_comm_ros::Percentage >::value();
  }
  static const char* value(const ::roah_rsbb_comm_ros::PercentageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roah_rsbb_comm_ros::PercentageResponse> should match
// service_traits::DataType< ::roah_rsbb_comm_ros::Percentage >
template<>
struct DataType< ::roah_rsbb_comm_ros::PercentageResponse>
{
  static const char* value()
  {
    return DataType< ::roah_rsbb_comm_ros::Percentage >::value();
  }
  static const char* value(const ::roah_rsbb_comm_ros::PercentageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROAH_RSBB_COMM_ROS_MESSAGE_PERCENTAGE_H
