// Generated by gencpp from file roah_rsbb_comm_ros/ResultHPPFRequest.msg
// DO NOT EDIT!


#ifndef ROAH_RSBB_COMM_ROS_MESSAGE_RESULTHPPFREQUEST_H
#define ROAH_RSBB_COMM_ROS_MESSAGE_RESULTHPPFREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace roah_rsbb_comm_ros
{
template <class ContainerAllocator>
struct ResultHPPFRequest_
{
  typedef ResultHPPFRequest_<ContainerAllocator> Type;

  ResultHPPFRequest_()
    : person_name()
    , person_pose()  {
    }
  ResultHPPFRequest_(const ContainerAllocator& _alloc)
    : person_name(_alloc)
    , person_pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _person_name_type;
  _person_name_type person_name;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _person_pose_type;
  _person_pose_type person_pose;





  typedef boost::shared_ptr< ::roah_rsbb_comm_ros::ResultHPPFRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roah_rsbb_comm_ros::ResultHPPFRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ResultHPPFRequest_

typedef ::roah_rsbb_comm_ros::ResultHPPFRequest_<std::allocator<void> > ResultHPPFRequest;

typedef boost::shared_ptr< ::roah_rsbb_comm_ros::ResultHPPFRequest > ResultHPPFRequestPtr;
typedef boost::shared_ptr< ::roah_rsbb_comm_ros::ResultHPPFRequest const> ResultHPPFRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roah_rsbb_comm_ros::ResultHPPFRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roah_rsbb_comm_ros::ResultHPPFRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roah_rsbb_comm_ros::ResultHPPFRequest_<ContainerAllocator1> & lhs, const ::roah_rsbb_comm_ros::ResultHPPFRequest_<ContainerAllocator2> & rhs)
{
  return lhs.person_name == rhs.person_name &&
    lhs.person_pose == rhs.person_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roah_rsbb_comm_ros::ResultHPPFRequest_<ContainerAllocator1> & lhs, const ::roah_rsbb_comm_ros::ResultHPPFRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roah_rsbb_comm_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roah_rsbb_comm_ros::ResultHPPFRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roah_rsbb_comm_ros::ResultHPPFRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roah_rsbb_comm_ros::ResultHPPFRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roah_rsbb_comm_ros::ResultHPPFRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roah_rsbb_comm_ros::ResultHPPFRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roah_rsbb_comm_ros::ResultHPPFRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roah_rsbb_comm_ros::ResultHPPFRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "879950a8a93ec363d8385cbe4b6a5d63";
  }

  static const char* value(const ::roah_rsbb_comm_ros::ResultHPPFRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x879950a8a93ec363ULL;
  static const uint64_t static_value2 = 0xd8385cbe4b6a5d63ULL;
};

template<class ContainerAllocator>
struct DataType< ::roah_rsbb_comm_ros::ResultHPPFRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roah_rsbb_comm_ros/ResultHPPFRequest";
  }

  static const char* value(const ::roah_rsbb_comm_ros::ResultHPPFRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roah_rsbb_comm_ros::ResultHPPFRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string person_name\n"
"geometry_msgs/Pose2D person_pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::roah_rsbb_comm_ros::ResultHPPFRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roah_rsbb_comm_ros::ResultHPPFRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.person_name);
      stream.next(m.person_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResultHPPFRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roah_rsbb_comm_ros::ResultHPPFRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roah_rsbb_comm_ros::ResultHPPFRequest_<ContainerAllocator>& v)
  {
    s << indent << "person_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.person_name);
    s << indent << "person_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.person_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROAH_RSBB_COMM_ROS_MESSAGE_RESULTHPPFREQUEST_H
