// Generated by gencpp from file roah_rsbb_comm_ros/ResultHOPF.msg
// DO NOT EDIT!


#ifndef ROAH_RSBB_COMM_ROS_MESSAGE_RESULTHOPF_H
#define ROAH_RSBB_COMM_ROS_MESSAGE_RESULTHOPF_H

#include <ros/service_traits.h>


#include <roah_rsbb_comm_ros/ResultHOPFRequest.h>
#include <roah_rsbb_comm_ros/ResultHOPFResponse.h>


namespace roah_rsbb_comm_ros
{

struct ResultHOPF
{

typedef ResultHOPFRequest Request;
typedef ResultHOPFResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResultHOPF
} // namespace roah_rsbb_comm_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roah_rsbb_comm_ros::ResultHOPF > {
  static const char* value()
  {
    return "712e1238eeaa80ac069f72dff01feb53";
  }

  static const char* value(const ::roah_rsbb_comm_ros::ResultHOPF&) { return value(); }
};

template<>
struct DataType< ::roah_rsbb_comm_ros::ResultHOPF > {
  static const char* value()
  {
    return "roah_rsbb_comm_ros/ResultHOPF";
  }

  static const char* value(const ::roah_rsbb_comm_ros::ResultHOPF&) { return value(); }
};


// service_traits::MD5Sum< ::roah_rsbb_comm_ros::ResultHOPFRequest> should match
// service_traits::MD5Sum< ::roah_rsbb_comm_ros::ResultHOPF >
template<>
struct MD5Sum< ::roah_rsbb_comm_ros::ResultHOPFRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roah_rsbb_comm_ros::ResultHOPF >::value();
  }
  static const char* value(const ::roah_rsbb_comm_ros::ResultHOPFRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roah_rsbb_comm_ros::ResultHOPFRequest> should match
// service_traits::DataType< ::roah_rsbb_comm_ros::ResultHOPF >
template<>
struct DataType< ::roah_rsbb_comm_ros::ResultHOPFRequest>
{
  static const char* value()
  {
    return DataType< ::roah_rsbb_comm_ros::ResultHOPF >::value();
  }
  static const char* value(const ::roah_rsbb_comm_ros::ResultHOPFRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roah_rsbb_comm_ros::ResultHOPFResponse> should match
// service_traits::MD5Sum< ::roah_rsbb_comm_ros::ResultHOPF >
template<>
struct MD5Sum< ::roah_rsbb_comm_ros::ResultHOPFResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roah_rsbb_comm_ros::ResultHOPF >::value();
  }
  static const char* value(const ::roah_rsbb_comm_ros::ResultHOPFResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roah_rsbb_comm_ros::ResultHOPFResponse> should match
// service_traits::DataType< ::roah_rsbb_comm_ros::ResultHOPF >
template<>
struct DataType< ::roah_rsbb_comm_ros::ResultHOPFResponse>
{
  static const char* value()
  {
    return DataType< ::roah_rsbb_comm_ros::ResultHOPF >::value();
  }
  static const char* value(const ::roah_rsbb_comm_ros::ResultHOPFResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROAH_RSBB_COMM_ROS_MESSAGE_RESULTHOPF_H
