// Generated by gencpp from file roah_rsbb_comm_ros/ResultHPPFResponse.msg
// DO NOT EDIT!


#ifndef ROAH_RSBB_COMM_ROS_MESSAGE_RESULTHPPFRESPONSE_H
#define ROAH_RSBB_COMM_ROS_MESSAGE_RESULTHPPFRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roah_rsbb_comm_ros
{
template <class ContainerAllocator>
struct ResultHPPFResponse_
{
  typedef ResultHPPFResponse_<ContainerAllocator> Type;

  ResultHPPFResponse_()
    {
    }
  ResultHPPFResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::roah_rsbb_comm_ros::ResultHPPFResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roah_rsbb_comm_ros::ResultHPPFResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ResultHPPFResponse_

typedef ::roah_rsbb_comm_ros::ResultHPPFResponse_<std::allocator<void> > ResultHPPFResponse;

typedef boost::shared_ptr< ::roah_rsbb_comm_ros::ResultHPPFResponse > ResultHPPFResponsePtr;
typedef boost::shared_ptr< ::roah_rsbb_comm_ros::ResultHPPFResponse const> ResultHPPFResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roah_rsbb_comm_ros::ResultHPPFResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roah_rsbb_comm_ros::ResultHPPFResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace roah_rsbb_comm_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roah_rsbb_comm_ros::ResultHPPFResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roah_rsbb_comm_ros::ResultHPPFResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roah_rsbb_comm_ros::ResultHPPFResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roah_rsbb_comm_ros::ResultHPPFResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roah_rsbb_comm_ros::ResultHPPFResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roah_rsbb_comm_ros::ResultHPPFResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roah_rsbb_comm_ros::ResultHPPFResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::roah_rsbb_comm_ros::ResultHPPFResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::roah_rsbb_comm_ros::ResultHPPFResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roah_rsbb_comm_ros/ResultHPPFResponse";
  }

  static const char* value(const ::roah_rsbb_comm_ros::ResultHPPFResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roah_rsbb_comm_ros::ResultHPPFResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::roah_rsbb_comm_ros::ResultHPPFResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roah_rsbb_comm_ros::ResultHPPFResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResultHPPFResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roah_rsbb_comm_ros::ResultHPPFResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::roah_rsbb_comm_ros::ResultHPPFResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROAH_RSBB_COMM_ROS_MESSAGE_RESULTHPPFRESPONSE_H
