// Generated by gencpp from file roah_rsbb_comm_ros/ResultHOPFResponse.msg
// DO NOT EDIT!


#ifndef ROAH_RSBB_COMM_ROS_MESSAGE_RESULTHOPFRESPONSE_H
#define ROAH_RSBB_COMM_ROS_MESSAGE_RESULTHOPFRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roah_rsbb_comm_ros
{
template <class ContainerAllocator>
struct ResultHOPFResponse_
{
  typedef ResultHOPFResponse_<ContainerAllocator> Type;

  ResultHOPFResponse_()
    {
    }
  ResultHOPFResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::roah_rsbb_comm_ros::ResultHOPFResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roah_rsbb_comm_ros::ResultHOPFResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ResultHOPFResponse_

typedef ::roah_rsbb_comm_ros::ResultHOPFResponse_<std::allocator<void> > ResultHOPFResponse;

typedef boost::shared_ptr< ::roah_rsbb_comm_ros::ResultHOPFResponse > ResultHOPFResponsePtr;
typedef boost::shared_ptr< ::roah_rsbb_comm_ros::ResultHOPFResponse const> ResultHOPFResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roah_rsbb_comm_ros::ResultHOPFResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roah_rsbb_comm_ros::ResultHOPFResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace roah_rsbb_comm_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roah_rsbb_comm_ros::ResultHOPFResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roah_rsbb_comm_ros::ResultHOPFResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roah_rsbb_comm_ros::ResultHOPFResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roah_rsbb_comm_ros::ResultHOPFResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roah_rsbb_comm_ros::ResultHOPFResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roah_rsbb_comm_ros::ResultHOPFResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roah_rsbb_comm_ros::ResultHOPFResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::roah_rsbb_comm_ros::ResultHOPFResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::roah_rsbb_comm_ros::ResultHOPFResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roah_rsbb_comm_ros/ResultHOPFResponse";
  }

  static const char* value(const ::roah_rsbb_comm_ros::ResultHOPFResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roah_rsbb_comm_ros::ResultHOPFResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::roah_rsbb_comm_ros::ResultHOPFResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roah_rsbb_comm_ros::ResultHOPFResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResultHOPFResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roah_rsbb_comm_ros::ResultHOPFResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::roah_rsbb_comm_ros::ResultHOPFResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROAH_RSBB_COMM_ROS_MESSAGE_RESULTHOPFRESPONSE_H
