// Generated by gencpp from file roah_rsbb_comm_ros/ResultHPPF.msg
// DO NOT EDIT!


#ifndef ROAH_RSBB_COMM_ROS_MESSAGE_RESULTHPPF_H
#define ROAH_RSBB_COMM_ROS_MESSAGE_RESULTHPPF_H

#include <ros/service_traits.h>


#include <roah_rsbb_comm_ros/ResultHPPFRequest.h>
#include <roah_rsbb_comm_ros/ResultHPPFResponse.h>


namespace roah_rsbb_comm_ros
{

struct ResultHPPF
{

typedef ResultHPPFRequest Request;
typedef ResultHPPFResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResultHPPF
} // namespace roah_rsbb_comm_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roah_rsbb_comm_ros::ResultHPPF > {
  static const char* value()
  {
    return "879950a8a93ec363d8385cbe4b6a5d63";
  }

  static const char* value(const ::roah_rsbb_comm_ros::ResultHPPF&) { return value(); }
};

template<>
struct DataType< ::roah_rsbb_comm_ros::ResultHPPF > {
  static const char* value()
  {
    return "roah_rsbb_comm_ros/ResultHPPF";
  }

  static const char* value(const ::roah_rsbb_comm_ros::ResultHPPF&) { return value(); }
};


// service_traits::MD5Sum< ::roah_rsbb_comm_ros::ResultHPPFRequest> should match
// service_traits::MD5Sum< ::roah_rsbb_comm_ros::ResultHPPF >
template<>
struct MD5Sum< ::roah_rsbb_comm_ros::ResultHPPFRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roah_rsbb_comm_ros::ResultHPPF >::value();
  }
  static const char* value(const ::roah_rsbb_comm_ros::ResultHPPFRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roah_rsbb_comm_ros::ResultHPPFRequest> should match
// service_traits::DataType< ::roah_rsbb_comm_ros::ResultHPPF >
template<>
struct DataType< ::roah_rsbb_comm_ros::ResultHPPFRequest>
{
  static const char* value()
  {
    return DataType< ::roah_rsbb_comm_ros::ResultHPPF >::value();
  }
  static const char* value(const ::roah_rsbb_comm_ros::ResultHPPFRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roah_rsbb_comm_ros::ResultHPPFResponse> should match
// service_traits::MD5Sum< ::roah_rsbb_comm_ros::ResultHPPF >
template<>
struct MD5Sum< ::roah_rsbb_comm_ros::ResultHPPFResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roah_rsbb_comm_ros::ResultHPPF >::value();
  }
  static const char* value(const ::roah_rsbb_comm_ros::ResultHPPFResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roah_rsbb_comm_ros::ResultHPPFResponse> should match
// service_traits::DataType< ::roah_rsbb_comm_ros::ResultHPPF >
template<>
struct DataType< ::roah_rsbb_comm_ros::ResultHPPFResponse>
{
  static const char* value()
  {
    return DataType< ::roah_rsbb_comm_ros::ResultHPPF >::value();
  }
  static const char* value(const ::roah_rsbb_comm_ros::ResultHPPFResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROAH_RSBB_COMM_ROS_MESSAGE_RESULTHPPF_H
