// Generated by gencpp from file roah_rsbb_comm_ros/String.msg
// DO NOT EDIT!


#ifndef ROAH_RSBB_COMM_ROS_MESSAGE_STRING_H
#define ROAH_RSBB_COMM_ROS_MESSAGE_STRING_H

#include <ros/service_traits.h>


#include <roah_rsbb_comm_ros/StringRequest.h>
#include <roah_rsbb_comm_ros/StringResponse.h>


namespace roah_rsbb_comm_ros
{

struct String
{

typedef StringRequest Request;
typedef StringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct String
} // namespace roah_rsbb_comm_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roah_rsbb_comm_ros::String > {
  static const char* value()
  {
    return "992ce8a1687cec8c8bd883ec73ca41d1";
  }

  static const char* value(const ::roah_rsbb_comm_ros::String&) { return value(); }
};

template<>
struct DataType< ::roah_rsbb_comm_ros::String > {
  static const char* value()
  {
    return "roah_rsbb_comm_ros/String";
  }

  static const char* value(const ::roah_rsbb_comm_ros::String&) { return value(); }
};


// service_traits::MD5Sum< ::roah_rsbb_comm_ros::StringRequest> should match
// service_traits::MD5Sum< ::roah_rsbb_comm_ros::String >
template<>
struct MD5Sum< ::roah_rsbb_comm_ros::StringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roah_rsbb_comm_ros::String >::value();
  }
  static const char* value(const ::roah_rsbb_comm_ros::StringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roah_rsbb_comm_ros::StringRequest> should match
// service_traits::DataType< ::roah_rsbb_comm_ros::String >
template<>
struct DataType< ::roah_rsbb_comm_ros::StringRequest>
{
  static const char* value()
  {
    return DataType< ::roah_rsbb_comm_ros::String >::value();
  }
  static const char* value(const ::roah_rsbb_comm_ros::StringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roah_rsbb_comm_ros::StringResponse> should match
// service_traits::MD5Sum< ::roah_rsbb_comm_ros::String >
template<>
struct MD5Sum< ::roah_rsbb_comm_ros::StringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roah_rsbb_comm_ros::String >::value();
  }
  static const char* value(const ::roah_rsbb_comm_ros::StringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roah_rsbb_comm_ros::StringResponse> should match
// service_traits::DataType< ::roah_rsbb_comm_ros::String >
template<>
struct DataType< ::roah_rsbb_comm_ros::StringResponse>
{
  static const char* value()
  {
    return DataType< ::roah_rsbb_comm_ros::String >::value();
  }
  static const char* value(const ::roah_rsbb_comm_ros::StringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROAH_RSBB_COMM_ROS_MESSAGE_STRING_H
