// Generated by gencpp from file gaan_msgs/Argument.msg
// DO NOT EDIT!


#ifndef GAAN_MSGS_MESSAGE_ARGUMENT_H
#define GAAN_MSGS_MESSAGE_ARGUMENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gaan_msgs
{
template <class ContainerAllocator>
struct Argument_
{
  typedef Argument_<ContainerAllocator> Type;

  Argument_()
    : arg_name()
    , role_filler()  {
    }
  Argument_(const ContainerAllocator& _alloc)
    : arg_name(_alloc)
    , role_filler(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _arg_name_type;
  _arg_name_type arg_name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _role_filler_type;
  _role_filler_type role_filler;





  typedef boost::shared_ptr< ::gaan_msgs::Argument_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gaan_msgs::Argument_<ContainerAllocator> const> ConstPtr;

}; // struct Argument_

typedef ::gaan_msgs::Argument_<std::allocator<void> > Argument;

typedef boost::shared_ptr< ::gaan_msgs::Argument > ArgumentPtr;
typedef boost::shared_ptr< ::gaan_msgs::Argument const> ArgumentConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gaan_msgs::Argument_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gaan_msgs::Argument_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gaan_msgs::Argument_<ContainerAllocator1> & lhs, const ::gaan_msgs::Argument_<ContainerAllocator2> & rhs)
{
  return lhs.arg_name == rhs.arg_name &&
    lhs.role_filler == rhs.role_filler;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gaan_msgs::Argument_<ContainerAllocator1> & lhs, const ::gaan_msgs::Argument_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gaan_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::gaan_msgs::Argument_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gaan_msgs::Argument_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gaan_msgs::Argument_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gaan_msgs::Argument_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gaan_msgs::Argument_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gaan_msgs::Argument_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gaan_msgs::Argument_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7648016a575af4d3576725405414910c";
  }

  static const char* value(const ::gaan_msgs::Argument_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7648016a575af4d3ULL;
  static const uint64_t static_value2 = 0x576725405414910cULL;
};

template<class ContainerAllocator>
struct DataType< ::gaan_msgs::Argument_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gaan_msgs/Argument";
  }

  static const char* value(const ::gaan_msgs::Argument_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gaan_msgs::Argument_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string arg_name\n"
"string role_filler\n"
;
  }

  static const char* value(const ::gaan_msgs::Argument_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gaan_msgs::Argument_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.arg_name);
      stream.next(m.role_filler);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Argument_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gaan_msgs::Argument_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gaan_msgs::Argument_<ContainerAllocator>& v)
  {
    s << indent << "arg_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.arg_name);
    s << indent << "role_filler: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.role_filler);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAAN_MSGS_MESSAGE_ARGUMENT_H
