// Generated by gencpp from file gaan_msgs/Command.msg
// DO NOT EDIT!


#ifndef GAAN_MSGS_MESSAGE_COMMAND_H
#define GAAN_MSGS_MESSAGE_COMMAND_H

#include <ros/service_traits.h>


#include <gaan_msgs/CommandRequest.h>
#include <gaan_msgs/CommandResponse.h>


namespace gaan_msgs
{

struct Command
{

typedef CommandRequest Request;
typedef CommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Command
} // namespace gaan_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gaan_msgs::Command > {
  static const char* value()
  {
    return "274e7ed7b6dcae63291eb98d6536980c";
  }

  static const char* value(const ::gaan_msgs::Command&) { return value(); }
};

template<>
struct DataType< ::gaan_msgs::Command > {
  static const char* value()
  {
    return "gaan_msgs/Command";
  }

  static const char* value(const ::gaan_msgs::Command&) { return value(); }
};


// service_traits::MD5Sum< ::gaan_msgs::CommandRequest> should match
// service_traits::MD5Sum< ::gaan_msgs::Command >
template<>
struct MD5Sum< ::gaan_msgs::CommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gaan_msgs::Command >::value();
  }
  static const char* value(const ::gaan_msgs::CommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gaan_msgs::CommandRequest> should match
// service_traits::DataType< ::gaan_msgs::Command >
template<>
struct DataType< ::gaan_msgs::CommandRequest>
{
  static const char* value()
  {
    return DataType< ::gaan_msgs::Command >::value();
  }
  static const char* value(const ::gaan_msgs::CommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gaan_msgs::CommandResponse> should match
// service_traits::MD5Sum< ::gaan_msgs::Command >
template<>
struct MD5Sum< ::gaan_msgs::CommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gaan_msgs::Command >::value();
  }
  static const char* value(const ::gaan_msgs::CommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gaan_msgs::CommandResponse> should match
// service_traits::DataType< ::gaan_msgs::Command >
template<>
struct DataType< ::gaan_msgs::CommandResponse>
{
  static const char* value()
  {
    return DataType< ::gaan_msgs::Command >::value();
  }
  static const char* value(const ::gaan_msgs::CommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAAN_MSGS_MESSAGE_COMMAND_H
