// Generated by gencpp from file gaan_msgs/FacesResponse.msg
// DO NOT EDIT!


#ifndef GAAN_MSGS_MESSAGE_FACESRESPONSE_H
#define GAAN_MSGS_MESSAGE_FACESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gaan_msgs
{
template <class ContainerAllocator>
struct FacesResponse_
{
  typedef FacesResponse_<ContainerAllocator> Type;

  FacesResponse_()
    : names()  {
    }
  FacesResponse_(const ContainerAllocator& _alloc)
    : names(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _names_type;
  _names_type names;





  typedef boost::shared_ptr< ::gaan_msgs::FacesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gaan_msgs::FacesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FacesResponse_

typedef ::gaan_msgs::FacesResponse_<std::allocator<void> > FacesResponse;

typedef boost::shared_ptr< ::gaan_msgs::FacesResponse > FacesResponsePtr;
typedef boost::shared_ptr< ::gaan_msgs::FacesResponse const> FacesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gaan_msgs::FacesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gaan_msgs::FacesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gaan_msgs::FacesResponse_<ContainerAllocator1> & lhs, const ::gaan_msgs::FacesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.names == rhs.names;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gaan_msgs::FacesResponse_<ContainerAllocator1> & lhs, const ::gaan_msgs::FacesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gaan_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::gaan_msgs::FacesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gaan_msgs::FacesResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gaan_msgs::FacesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gaan_msgs::FacesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gaan_msgs::FacesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gaan_msgs::FacesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gaan_msgs::FacesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dc7ae3609524b18034e49294a4ce670e";
  }

  static const char* value(const ::gaan_msgs::FacesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdc7ae3609524b180ULL;
  static const uint64_t static_value2 = 0x34e49294a4ce670eULL;
};

template<class ContainerAllocator>
struct DataType< ::gaan_msgs::FacesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gaan_msgs/FacesResponse";
  }

  static const char* value(const ::gaan_msgs::FacesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gaan_msgs::FacesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] names\n"
"\n"
;
  }

  static const char* value(const ::gaan_msgs::FacesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gaan_msgs::FacesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.names);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FacesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gaan_msgs::FacesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gaan_msgs::FacesResponse_<ContainerAllocator>& v)
  {
    s << indent << "names[]" << std::endl;
    for (size_t i = 0; i < v.names.size(); ++i)
    {
      s << indent << "  names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.names[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAAN_MSGS_MESSAGE_FACESRESPONSE_H
