// Generated by gencpp from file gaan_msgs/FacesRequest.msg
// DO NOT EDIT!


#ifndef GAAN_MSGS_MESSAGE_FACESREQUEST_H
#define GAAN_MSGS_MESSAGE_FACESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gaan_msgs
{
template <class ContainerAllocator>
struct FacesRequest_
{
  typedef FacesRequest_<ContainerAllocator> Type;

  FacesRequest_()
    {
    }
  FacesRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::gaan_msgs::FacesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gaan_msgs::FacesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FacesRequest_

typedef ::gaan_msgs::FacesRequest_<std::allocator<void> > FacesRequest;

typedef boost::shared_ptr< ::gaan_msgs::FacesRequest > FacesRequestPtr;
typedef boost::shared_ptr< ::gaan_msgs::FacesRequest const> FacesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gaan_msgs::FacesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gaan_msgs::FacesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace gaan_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::gaan_msgs::FacesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gaan_msgs::FacesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gaan_msgs::FacesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gaan_msgs::FacesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gaan_msgs::FacesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gaan_msgs::FacesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gaan_msgs::FacesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::gaan_msgs::FacesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::gaan_msgs::FacesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gaan_msgs/FacesRequest";
  }

  static const char* value(const ::gaan_msgs::FacesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gaan_msgs::FacesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::gaan_msgs::FacesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gaan_msgs::FacesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FacesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gaan_msgs::FacesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::gaan_msgs::FacesRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // GAAN_MSGS_MESSAGE_FACESREQUEST_H
