// Generated by gencpp from file gaan_msgs/Faces.msg
// DO NOT EDIT!


#ifndef GAAN_MSGS_MESSAGE_FACES_H
#define GAAN_MSGS_MESSAGE_FACES_H

#include <ros/service_traits.h>


#include <gaan_msgs/FacesRequest.h>
#include <gaan_msgs/FacesResponse.h>


namespace gaan_msgs
{

struct Faces
{

typedef FacesRequest Request;
typedef FacesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Faces
} // namespace gaan_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gaan_msgs::Faces > {
  static const char* value()
  {
    return "dc7ae3609524b18034e49294a4ce670e";
  }

  static const char* value(const ::gaan_msgs::Faces&) { return value(); }
};

template<>
struct DataType< ::gaan_msgs::Faces > {
  static const char* value()
  {
    return "gaan_msgs/Faces";
  }

  static const char* value(const ::gaan_msgs::Faces&) { return value(); }
};


// service_traits::MD5Sum< ::gaan_msgs::FacesRequest> should match
// service_traits::MD5Sum< ::gaan_msgs::Faces >
template<>
struct MD5Sum< ::gaan_msgs::FacesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gaan_msgs::Faces >::value();
  }
  static const char* value(const ::gaan_msgs::FacesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gaan_msgs::FacesRequest> should match
// service_traits::DataType< ::gaan_msgs::Faces >
template<>
struct DataType< ::gaan_msgs::FacesRequest>
{
  static const char* value()
  {
    return DataType< ::gaan_msgs::Faces >::value();
  }
  static const char* value(const ::gaan_msgs::FacesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gaan_msgs::FacesResponse> should match
// service_traits::MD5Sum< ::gaan_msgs::Faces >
template<>
struct MD5Sum< ::gaan_msgs::FacesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gaan_msgs::Faces >::value();
  }
  static const char* value(const ::gaan_msgs::FacesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gaan_msgs::FacesResponse> should match
// service_traits::DataType< ::gaan_msgs::Faces >
template<>
struct DataType< ::gaan_msgs::FacesResponse>
{
  static const char* value()
  {
    return DataType< ::gaan_msgs::Faces >::value();
  }
  static const char* value(const ::gaan_msgs::FacesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAAN_MSGS_MESSAGE_FACES_H
