// Generated by gencpp from file gaan_msgs/Manipulate.msg
// DO NOT EDIT!


#ifndef GAAN_MSGS_MESSAGE_MANIPULATE_H
#define GAAN_MSGS_MESSAGE_MANIPULATE_H

#include <ros/service_traits.h>


#include <gaan_msgs/ManipulateRequest.h>
#include <gaan_msgs/ManipulateResponse.h>


namespace gaan_msgs
{

struct Manipulate
{

typedef ManipulateRequest Request;
typedef ManipulateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Manipulate
} // namespace gaan_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gaan_msgs::Manipulate > {
  static const char* value()
  {
    return "6e3d3a215d14edaa77b01b5d2ec6e5a7";
  }

  static const char* value(const ::gaan_msgs::Manipulate&) { return value(); }
};

template<>
struct DataType< ::gaan_msgs::Manipulate > {
  static const char* value()
  {
    return "gaan_msgs/Manipulate";
  }

  static const char* value(const ::gaan_msgs::Manipulate&) { return value(); }
};


// service_traits::MD5Sum< ::gaan_msgs::ManipulateRequest> should match
// service_traits::MD5Sum< ::gaan_msgs::Manipulate >
template<>
struct MD5Sum< ::gaan_msgs::ManipulateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gaan_msgs::Manipulate >::value();
  }
  static const char* value(const ::gaan_msgs::ManipulateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gaan_msgs::ManipulateRequest> should match
// service_traits::DataType< ::gaan_msgs::Manipulate >
template<>
struct DataType< ::gaan_msgs::ManipulateRequest>
{
  static const char* value()
  {
    return DataType< ::gaan_msgs::Manipulate >::value();
  }
  static const char* value(const ::gaan_msgs::ManipulateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gaan_msgs::ManipulateResponse> should match
// service_traits::MD5Sum< ::gaan_msgs::Manipulate >
template<>
struct MD5Sum< ::gaan_msgs::ManipulateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gaan_msgs::Manipulate >::value();
  }
  static const char* value(const ::gaan_msgs::ManipulateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gaan_msgs::ManipulateResponse> should match
// service_traits::DataType< ::gaan_msgs::Manipulate >
template<>
struct DataType< ::gaan_msgs::ManipulateResponse>
{
  static const char* value()
  {
    return DataType< ::gaan_msgs::Manipulate >::value();
  }
  static const char* value(const ::gaan_msgs::ManipulateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAAN_MSGS_MESSAGE_MANIPULATE_H
