// Generated by gencpp from file gaan_msgs/ManipulateResponse.msg
// DO NOT EDIT!


#ifndef GAAN_MSGS_MESSAGE_MANIPULATERESPONSE_H
#define GAAN_MSGS_MESSAGE_MANIPULATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gaan_msgs
{
template <class ContainerAllocator>
struct ManipulateResponse_
{
  typedef ManipulateResponse_<ContainerAllocator> Type;

  ManipulateResponse_()
    : response(false)  {
    }
  ManipulateResponse_(const ContainerAllocator& _alloc)
    : response(false)  {
  (void)_alloc;
    }



   typedef uint8_t _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::gaan_msgs::ManipulateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gaan_msgs::ManipulateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ManipulateResponse_

typedef ::gaan_msgs::ManipulateResponse_<std::allocator<void> > ManipulateResponse;

typedef boost::shared_ptr< ::gaan_msgs::ManipulateResponse > ManipulateResponsePtr;
typedef boost::shared_ptr< ::gaan_msgs::ManipulateResponse const> ManipulateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gaan_msgs::ManipulateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gaan_msgs::ManipulateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gaan_msgs::ManipulateResponse_<ContainerAllocator1> & lhs, const ::gaan_msgs::ManipulateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gaan_msgs::ManipulateResponse_<ContainerAllocator1> & lhs, const ::gaan_msgs::ManipulateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gaan_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::gaan_msgs::ManipulateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gaan_msgs::ManipulateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gaan_msgs::ManipulateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gaan_msgs::ManipulateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gaan_msgs::ManipulateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gaan_msgs::ManipulateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gaan_msgs::ManipulateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "003b81baa95ab323fc1ddf3c7d0bee81";
  }

  static const char* value(const ::gaan_msgs::ManipulateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x003b81baa95ab323ULL;
  static const uint64_t static_value2 = 0xfc1ddf3c7d0bee81ULL;
};

template<class ContainerAllocator>
struct DataType< ::gaan_msgs::ManipulateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gaan_msgs/ManipulateResponse";
  }

  static const char* value(const ::gaan_msgs::ManipulateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gaan_msgs::ManipulateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool response\n"
"\n"
"\n"
;
  }

  static const char* value(const ::gaan_msgs::ManipulateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gaan_msgs::ManipulateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ManipulateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gaan_msgs::ManipulateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gaan_msgs::ManipulateResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAAN_MSGS_MESSAGE_MANIPULATERESPONSE_H
