// Generated by gencpp from file gaan_msgs/NavigateTo.msg
// DO NOT EDIT!


#ifndef GAAN_MSGS_MESSAGE_NAVIGATETO_H
#define GAAN_MSGS_MESSAGE_NAVIGATETO_H

#include <ros/service_traits.h>


#include <gaan_msgs/NavigateToRequest.h>
#include <gaan_msgs/NavigateToResponse.h>


namespace gaan_msgs
{

struct NavigateTo
{

typedef NavigateToRequest Request;
typedef NavigateToResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NavigateTo
} // namespace gaan_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gaan_msgs::NavigateTo > {
  static const char* value()
  {
    return "1d3c815fa4fd2c21ffd36bbca1e530bf";
  }

  static const char* value(const ::gaan_msgs::NavigateTo&) { return value(); }
};

template<>
struct DataType< ::gaan_msgs::NavigateTo > {
  static const char* value()
  {
    return "gaan_msgs/NavigateTo";
  }

  static const char* value(const ::gaan_msgs::NavigateTo&) { return value(); }
};


// service_traits::MD5Sum< ::gaan_msgs::NavigateToRequest> should match
// service_traits::MD5Sum< ::gaan_msgs::NavigateTo >
template<>
struct MD5Sum< ::gaan_msgs::NavigateToRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gaan_msgs::NavigateTo >::value();
  }
  static const char* value(const ::gaan_msgs::NavigateToRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gaan_msgs::NavigateToRequest> should match
// service_traits::DataType< ::gaan_msgs::NavigateTo >
template<>
struct DataType< ::gaan_msgs::NavigateToRequest>
{
  static const char* value()
  {
    return DataType< ::gaan_msgs::NavigateTo >::value();
  }
  static const char* value(const ::gaan_msgs::NavigateToRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gaan_msgs::NavigateToResponse> should match
// service_traits::MD5Sum< ::gaan_msgs::NavigateTo >
template<>
struct MD5Sum< ::gaan_msgs::NavigateToResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gaan_msgs::NavigateTo >::value();
  }
  static const char* value(const ::gaan_msgs::NavigateToResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gaan_msgs::NavigateToResponse> should match
// service_traits::DataType< ::gaan_msgs::NavigateTo >
template<>
struct DataType< ::gaan_msgs::NavigateToResponse>
{
  static const char* value()
  {
    return DataType< ::gaan_msgs::NavigateTo >::value();
  }
  static const char* value(const ::gaan_msgs::NavigateToResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAAN_MSGS_MESSAGE_NAVIGATETO_H
