// Generated by gencpp from file gaan_msgs/Speech.msg
// DO NOT EDIT!


#ifndef GAAN_MSGS_MESSAGE_SPEECH_H
#define GAAN_MSGS_MESSAGE_SPEECH_H

#include <ros/service_traits.h>


#include <gaan_msgs/SpeechRequest.h>
#include <gaan_msgs/SpeechResponse.h>


namespace gaan_msgs
{

struct Speech
{

typedef SpeechRequest Request;
typedef SpeechResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Speech
} // namespace gaan_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gaan_msgs::Speech > {
  static const char* value()
  {
    return "d4dde95938bb106b3c23e1eff4e5e29a";
  }

  static const char* value(const ::gaan_msgs::Speech&) { return value(); }
};

template<>
struct DataType< ::gaan_msgs::Speech > {
  static const char* value()
  {
    return "gaan_msgs/Speech";
  }

  static const char* value(const ::gaan_msgs::Speech&) { return value(); }
};


// service_traits::MD5Sum< ::gaan_msgs::SpeechRequest> should match
// service_traits::MD5Sum< ::gaan_msgs::Speech >
template<>
struct MD5Sum< ::gaan_msgs::SpeechRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gaan_msgs::Speech >::value();
  }
  static const char* value(const ::gaan_msgs::SpeechRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gaan_msgs::SpeechRequest> should match
// service_traits::DataType< ::gaan_msgs::Speech >
template<>
struct DataType< ::gaan_msgs::SpeechRequest>
{
  static const char* value()
  {
    return DataType< ::gaan_msgs::Speech >::value();
  }
  static const char* value(const ::gaan_msgs::SpeechRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gaan_msgs::SpeechResponse> should match
// service_traits::MD5Sum< ::gaan_msgs::Speech >
template<>
struct MD5Sum< ::gaan_msgs::SpeechResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gaan_msgs::Speech >::value();
  }
  static const char* value(const ::gaan_msgs::SpeechResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gaan_msgs::SpeechResponse> should match
// service_traits::DataType< ::gaan_msgs::Speech >
template<>
struct DataType< ::gaan_msgs::SpeechResponse>
{
  static const char* value()
  {
    return DataType< ::gaan_msgs::Speech >::value();
  }
  static const char* value(const ::gaan_msgs::SpeechResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAAN_MSGS_MESSAGE_SPEECH_H
