set(pal_robotiq_gripper_wrapper_msgs_MESSAGE_FILES "/home/hsr/tiago_public_ws/src/pal_robotiq_gripper/pal_robotiq_gripper_wrapper_msgs/msg/GripperStatus.msg")
set(pal_robotiq_gripper_wrapper_msgs_SERVICE_FILES "")
