# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from roah_rsbb_comm_ros/TabletState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class TabletState(genpy.Message):
  _md5sum = "e22a07b846b70880201a367bc6f1c8a3"
  _type = "roah_rsbb_comm_ros/TabletState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool display_map
time call_time
time position_time
float64 position_x
float64 position_y
"""
  __slots__ = ['display_map','call_time','position_time','position_x','position_y']
  _slot_types = ['bool','time','time','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       display_map,call_time,position_time,position_x,position_y

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TabletState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.display_map is None:
        self.display_map = False
      if self.call_time is None:
        self.call_time = genpy.Time()
      if self.position_time is None:
        self.position_time = genpy.Time()
      if self.position_x is None:
        self.position_x = 0.
      if self.position_y is None:
        self.position_y = 0.
    else:
      self.display_map = False
      self.call_time = genpy.Time()
      self.position_time = genpy.Time()
      self.position_x = 0.
      self.position_y = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B4I2d().pack(_x.display_map, _x.call_time.secs, _x.call_time.nsecs, _x.position_time.secs, _x.position_time.nsecs, _x.position_x, _x.position_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.call_time is None:
        self.call_time = genpy.Time()
      if self.position_time is None:
        self.position_time = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 33
      (_x.display_map, _x.call_time.secs, _x.call_time.nsecs, _x.position_time.secs, _x.position_time.nsecs, _x.position_x, _x.position_y,) = _get_struct_B4I2d().unpack(str[start:end])
      self.display_map = bool(self.display_map)
      self.call_time.canon()
      self.position_time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B4I2d().pack(_x.display_map, _x.call_time.secs, _x.call_time.nsecs, _x.position_time.secs, _x.position_time.nsecs, _x.position_x, _x.position_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.call_time is None:
        self.call_time = genpy.Time()
      if self.position_time is None:
        self.position_time = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 33
      (_x.display_map, _x.call_time.secs, _x.call_time.nsecs, _x.position_time.secs, _x.position_time.nsecs, _x.position_x, _x.position_y,) = _get_struct_B4I2d().unpack(str[start:end])
      self.display_map = bool(self.display_map)
      self.call_time.canon()
      self.position_time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B4I2d = None
def _get_struct_B4I2d():
    global _struct_B4I2d
    if _struct_B4I2d is None:
        _struct_B4I2d = struct.Struct("<B4I2d")
    return _struct_B4I2d
